// GET MOVIES
export const GET_ALL_MOVIES = 'GET_ALL_MOVIES';
export const GET_LIKED_MOVIES = 'GET_LIKED_MOVIES';
export const GET_BLOCKED_MOVIES = 'GET_BLOCKED_MOVIES';
// ADD DELETE 
export const ADD_LIKED_MOVIES = 'ADD_LIKED_MOVIES';
export const DELETE_LIKED_MOVIES = 'DELETE_LIKED_MOVIES';
export const ADD_BLOCKED_MOVIES = 'ADD_BLOCKED_MOVIES';
export const DELETE_BLOCKED_MOVIES = 'DELETE_BLOCKED_MOVIES';
// ERRORS 
export const GET_MOVIES_ERRORS = 'GET_MOVIES_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
// LOADING
export const MOVIES_LOADING = 'MOVIES_LOADING';
// CHANGE PAGE
export const CHANGE_PAGE = 'CHANGE_PAGE';
//GET GET_TOTAL_PAGES
export const GET_TOTAL_PAGES = 'GET_TOTAL_PAGES';

export const SET_SORT = 'SET_SORT';








